products = [
  {
    '_id': "1",
    'name': "Boots",
    'image': "/images/Boots.jpeg",
    'description': "Harry Cane king back",
    'brand': "Adidas",
    'category': "Shoes",
    'price': 209.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  }, {
    '_id': "2",
    'name': "Football",
    'image': "/images/Football.jpeg",
    'description': "Euro Cup 2020 official football",
    'brand': "Adidas",
    'category': "Accessories",
    'price': 129.99,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': "3",
    'name': "France Uniform",
    'image': "/images/France.jpeg",
    'description': "France Euro 2020 Uniform",
    'brand': "Nike",
    'category': "Sportswear",
    'price': 99.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': "4",
    'name': "Italy Uniform",
    'image': "/images/Italy.jpeg",
    'description': "Italy Euro 2020 Uniform",
    'brand': "Adidas",
    'category': "Sportswear",
    'price': 99.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': "5",
    'name': "Euro Mug",
    'image': "/images/Mug.jpeg",
    'description': "Euro 2020 Tea Mug",
    'brand': "Logitech",
    'category': "Accessories",
    'price': 19.99,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': "6",
    'name': "Spain Uniform",
    'image': "/images/Spain.jpeg",
    'description': "Spain Euro 2020 Uniform",
    'brand': "Nike",
    'category': "Sportswear",
    'price': 99.99,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
];

